"""Add GradingScale and department

Revision ID: 01528cc8f6e0
Revises: 9fe543685fd7
Create Date: 2026-08-18 01:48:25.074256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01528cc8f6e0'
down_revision: Union[str, Sequence[str], None] = '9fe543685fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_scales',
    sa.Column('grade_name', sa.String(), nullable=False),
    sa.Column('min_marks', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('grade_point', sa.Float(), nullable=False),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_grading_scales_is_deleted'), 'grading_scales', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_grading_scales_tenant_id'), 'grading_scales', ['tenant_id'], unique=False, schema='exam')
    op.add_column('classes', sa.Column('department', sa.String(), nullable=True), schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'department', schema='academic')
    op.drop_index(op.f('ix_exam_grading_scales_tenant_id'), table_name='grading_scales', schema='exam')
    op.drop_index(op.f('ix_exam_grading_scales_is_deleted'), table_name='grading_scales', schema='exam')
    op.drop_table('grading_scales', schema='exam')
    # ### end Alembic commands ###
