"""Add Department table and department_id to Class

Revision ID: 09429cb4dff3
Revises: 01528cc8f6e0
Create Date: 2026-08-18 02:34:44.198238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09429cb4dff3'
down_revision: Union[str, Sequence[str], None] = '01528cc8f6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_departments_is_deleted'), 'departments', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_departments_tenant_id'), 'departments', ['tenant_id'], unique=False, schema='academic')
    op.add_column('classes', sa.Column('department_id', sa.Uuid(), nullable=True), schema='academic')
    op.create_foreign_key(None, 'classes', 'departments', ['department_id'], ['id'], source_schema='academic', referent_schema='academic')
    op.drop_column('classes', 'department', schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True), schema='academic')
    op.drop_constraint(None, 'classes', schema='academic', type_='foreignkey')
    op.drop_column('classes', 'department_id', schema='academic')
    op.drop_index(op.f('ix_academic_departments_tenant_id'), table_name='departments', schema='academic')
    op.drop_index(op.f('ix_academic_departments_is_deleted'), table_name='departments', schema='academic')
    op.drop_table('departments', schema='academic')
    # ### end Alembic commands ###
