"""Add max_failing_subjects to Exam

Revision ID: 1e3aca4a4b49
Revises: 09429cb4dff3
Create Date: 2026-08-18 02:45:58.218170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3aca4a4b49'
down_revision: Union[str, Sequence[str], None] = '09429cb4dff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('max_failing_subjects', sa.Integer(), nullable=False, server_default='0'), schema='exam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'max_failing_subjects', schema='exam')
    # ### end Alembic commands ###
