"""Add yearly class subject booleans and exam result status

Revision ID: 2c73862d10ff
Revises: 47404ed7bb09
Create Date: 2026-08-19 07:10:19.580890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c73862d10ff'
down_revision: Union[str, Sequence[str], None] = '47404ed7bb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_class_subjects', sa.Column('is_main_subject', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='academic')
    op.add_column('yearly_class_subjects', sa.Column('affects_result_calculation', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='academic')
    op.add_column('exam_results', sa.Column('status', sa.String(), server_default='PRESENT', nullable=False), schema='exam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_results', 'status', schema='exam')
    op.drop_column('yearly_class_subjects', 'affects_result_calculation', schema='academic')
    op.drop_column('yearly_class_subjects', 'is_main_subject', schema='academic')
    # ### end Alembic commands ###
