"""
Add exam_boards and exam_registrations

Revision ID: 3c27be385a0c
Revises: e5f6a1b2c3d4
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c27be385a0c'
down_revision: Union[str, None] = 'e5f6a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exam_boards_is_deleted'), 'exam_boards', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_boards_organization_id'), 'exam_boards', ['organization_id'], unique=False, schema='exam')
    
    op.create_table('exam_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('exam_type_id', sa.Integer(), nullable=False),
    sa.Column('exam_board_id', sa.Integer(), nullable=True),
    sa.Column('board_roll_no', sa.String(length=50), nullable=True),
    sa.Column('board_registration_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['academic.enrollments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_board_id'], ['exam.exam_boards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam.exam_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'exam_type_id', name='uq_exam_registration_enroll_exam'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exam_registrations_enrollment_id'), 'exam_registrations', ['enrollment_id'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_registrations_exam_board_id'), 'exam_registrations', ['exam_board_id'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_registrations_exam_type_id'), 'exam_registrations', ['exam_type_id'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_registrations_is_deleted'), 'exam_registrations', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_registrations_organization_id'), 'exam_registrations', ['organization_id'], unique=False, schema='exam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_exam_registrations_organization_id'), table_name='exam_registrations', schema='exam')
    op.drop_index(op.f('ix_exam_exam_registrations_is_deleted'), table_name='exam_registrations', schema='exam')
    op.drop_index(op.f('ix_exam_exam_registrations_exam_type_id'), table_name='exam_registrations', schema='exam')
    op.drop_index(op.f('ix_exam_exam_registrations_exam_board_id'), table_name='exam_registrations', schema='exam')
    op.drop_index(op.f('ix_exam_exam_registrations_enrollment_id'), table_name='exam_registrations', schema='exam')
    op.drop_table('exam_registrations', schema='exam')
    op.drop_index(op.f('ix_exam_exam_boards_organization_id'), table_name='exam_boards', schema='exam')
    op.drop_index(op.f('ix_exam_exam_boards_is_deleted'), table_name='exam_boards', schema='exam')
    op.drop_table('exam_boards', schema='exam')
    # ### end Alembic commands ###
