"""Schema separated models

Revision ID: 4272230197ad
Revises: 
Create Date: 2026-08-18 01:10:16.538085

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4272230197ad'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_academic_years_is_deleted'), 'academic_years', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False, schema='academic')
    op.create_table('classes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_classes_is_deleted'), 'classes', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_classes_tenant_id'), 'classes', ['tenant_id'], unique=False, schema='academic')
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_roles_is_deleted'), 'roles', ['is_deleted'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_roles_tenant_id'), 'roles', ['tenant_id'], unique=False, schema='auth')
    op.create_table('branches',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_branches_is_deleted'), 'branches', ['is_deleted'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_branches_tenant_id'), 'branches', ['tenant_id'], unique=False, schema='tenant')
    op.create_table('institutes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_institutes_is_deleted'), 'institutes', ['is_deleted'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_institutes_name'), 'institutes', ['name'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_institutes_slug'), 'institutes', ['slug'], unique=True, schema='tenant')
    op.create_table('sections',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['tenant.branches.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_sections_is_deleted'), 'sections', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_sections_tenant_id'), 'sections', ['tenant_id'], unique=False, schema='academic')
    op.create_table('semesters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_semesters_is_deleted'), 'semesters', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_semesters_tenant_id'), 'semesters', ['tenant_id'], unique=False, schema='academic')
    op.create_table('subjects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_subjects_is_deleted'), 'subjects', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False, schema='academic')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['tenant.branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_is_deleted'), 'users', ['is_deleted'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_tenant_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_is_deleted'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_index(op.f('ix_academic_subjects_tenant_id'), table_name='subjects', schema='academic')
    op.drop_index(op.f('ix_academic_subjects_is_deleted'), table_name='subjects', schema='academic')
    op.drop_table('subjects', schema='academic')
    op.drop_index(op.f('ix_academic_semesters_tenant_id'), table_name='semesters', schema='academic')
    op.drop_index(op.f('ix_academic_semesters_is_deleted'), table_name='semesters', schema='academic')
    op.drop_table('semesters', schema='academic')
    op.drop_index(op.f('ix_academic_sections_tenant_id'), table_name='sections', schema='academic')
    op.drop_index(op.f('ix_academic_sections_is_deleted'), table_name='sections', schema='academic')
    op.drop_table('sections', schema='academic')
    op.drop_index(op.f('ix_tenant_institutes_slug'), table_name='institutes', schema='tenant')
    op.drop_index(op.f('ix_tenant_institutes_name'), table_name='institutes', schema='tenant')
    op.drop_index(op.f('ix_tenant_institutes_is_deleted'), table_name='institutes', schema='tenant')
    op.drop_table('institutes', schema='tenant')
    op.drop_index(op.f('ix_tenant_branches_tenant_id'), table_name='branches', schema='tenant')
    op.drop_index(op.f('ix_tenant_branches_is_deleted'), table_name='branches', schema='tenant')
    op.drop_table('branches', schema='tenant')
    op.drop_index(op.f('ix_auth_roles_tenant_id'), table_name='roles', schema='auth')
    op.drop_index(op.f('ix_auth_roles_is_deleted'), table_name='roles', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index(op.f('ix_academic_classes_tenant_id'), table_name='classes', schema='academic')
    op.drop_index(op.f('ix_academic_classes_is_deleted'), table_name='classes', schema='academic')
    op.drop_table('classes', schema='academic')
    op.drop_index(op.f('ix_academic_academic_years_tenant_id'), table_name='academic_years', schema='academic')
    op.drop_index(op.f('ix_academic_academic_years_is_deleted'), table_name='academic_years', schema='academic')
    op.drop_table('academic_years', schema='academic')
    # ### end Alembic commands ###
