"""replace_academic_year_class_with_yearly_class_subject

Revision ID: 47404ed7bb09
Revises: e190882b3696
Create Date: 2026-08-18 17:48:30.019048

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47404ed7bb09'
down_revision: str | Sequence[str] | None = 'e190882b3696'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearly_class_subjects',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['academic.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_yearly_class_subjects_is_deleted'), 'yearly_class_subjects', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_yearly_class_subjects_tenant_id'), 'yearly_class_subjects', ['tenant_id'], unique=False, schema='academic')
    op.drop_index(op.f('ix_academic_academic_year_classes_is_deleted'), table_name='academic_year_classes', schema='academic')
    op.drop_index(op.f('ix_academic_academic_year_classes_tenant_id'), table_name='academic_year_classes', schema='academic')
    op.drop_table('academic_year_classes', schema='academic')
    op.drop_constraint(op.f('subjects_class_id_fkey'), 'subjects', schema='academic', type_='foreignkey')
    op.drop_column('subjects', 'class_id', schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False), schema='academic')
    op.create_foreign_key(op.f('subjects_class_id_fkey'), 'subjects', 'classes', ['class_id'], ['id'], source_schema='academic', referent_schema='academic')
    op.create_table('academic_year_classes',
    sa.Column('academic_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], name=op.f('academic_year_classes_academic_year_id_fkey')),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], name=op.f('academic_year_classes_class_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_year_classes_pkey')),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_academic_year_classes_tenant_id'), 'academic_year_classes', ['tenant_id'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_academic_year_classes_is_deleted'), 'academic_year_classes', ['is_deleted'], unique=False, schema='academic')
    op.drop_index(op.f('ix_academic_yearly_class_subjects_tenant_id'), table_name='yearly_class_subjects', schema='academic')
    op.drop_index(op.f('ix_academic_yearly_class_subjects_is_deleted'), table_name='yearly_class_subjects', schema='academic')
    op.drop_table('yearly_class_subjects', schema='academic')
    # ### end Alembic commands ###
