"""Add student_id_no

Revision ID: 776f7cf8e1e7
Revises: 2c73862d10ff
Create Date: 2026-08-30 15:27:05.697201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776f7cf8e1e7'
down_revision: Union[str, Sequence[str], None] = '2c73862d10ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id_no', sa.Integer(), nullable=False), schema='student')
    op.create_index(op.f('ix_student_students_student_id_no'), 'students', ['student_id_no'], unique=True, schema='student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_students_student_id_no'), table_name='students', schema='student')
    op.drop_column('students', 'student_id_no', schema='student')
    # ### end Alembic commands ###
