"""ExamSchedule class_id and times

Revision ID: 81588816130f
Revises: 83b09189faf7
Create Date: 2026-08-30 21:11:39.393169

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81588816130f'
down_revision: str | Sequence[str] | None = '83b09189faf7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_schedules', sa.Column('class_id', sa.Uuid(), nullable=False), schema='exam')
    op.alter_column('exam_schedules', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='exam')
    op.alter_column('exam_schedules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='exam')
    op.create_foreign_key(None, 'exam_schedules', 'classes', ['class_id'], ['id'], source_schema='exam', referent_schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_schedules', schema='exam', type_='foreignkey')
    op.alter_column('exam_schedules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='exam')
    op.alter_column('exam_schedules', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='exam')
    op.drop_column('exam_schedules', 'class_id', schema='exam')
    # ### end Alembic commands ###
