"""Remove enrollment_number

Revision ID: 83b09189faf7
Revises: 776f7cf8e1e7
Create Date: 2026-08-30 15:43:39.064982

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83b09189faf7'
down_revision: str | Sequence[str] | None = '776f7cf8e1e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_enrollments_enrollment_number'), table_name='enrollments', schema='student')
    op.drop_column('enrollments', 'enrollment_number', schema='student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('enrollment_number', sa.VARCHAR(), autoincrement=False, nullable=False), schema='student')
    op.create_index(op.f('ix_student_enrollments_enrollment_number'), 'enrollments', ['enrollment_number'], unique=False, schema='student')
    # ### end Alembic commands ###
