"""Add Shift and AcademicYearClass

Revision ID: 854e092a8503
Revises: 1e3aca4a4b49
Create Date: 2026-08-18 16:57:35.634632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854e092a8503'
down_revision: Union[str, Sequence[str], None] = '1e3aca4a4b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_shifts_is_deleted'), 'shifts', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False, schema='academic')
    op.create_table('academic_year_classes',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_academic_year_classes_is_deleted'), 'academic_year_classes', ['is_deleted'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_academic_year_classes_tenant_id'), 'academic_year_classes', ['tenant_id'], unique=False, schema='academic')
    op.add_column('sections', sa.Column('shift_id', sa.Uuid(), nullable=True), schema='academic')
    op.create_foreign_key(None, 'sections', 'shifts', ['shift_id'], ['id'], source_schema='academic', referent_schema='academic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', schema='academic', type_='foreignkey')
    op.drop_column('sections', 'shift_id', schema='academic')
    op.drop_index(op.f('ix_academic_academic_year_classes_tenant_id'), table_name='academic_year_classes', schema='academic')
    op.drop_index(op.f('ix_academic_academic_year_classes_is_deleted'), table_name='academic_year_classes', schema='academic')
    op.drop_table('academic_year_classes', schema='academic')
    op.drop_index(op.f('ix_academic_shifts_tenant_id'), table_name='shifts', schema='academic')
    op.drop_index(op.f('ix_academic_shifts_is_deleted'), table_name='shifts', schema='academic')
    op.drop_table('shifts', schema='academic')
    # ### end Alembic commands ###
