"""Add Exam Models

Revision ID: 9fe543685fd7
Revises: d1a02fc42224
Create Date: 2026-08-18 01:27:39.235000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe543685fd7'
down_revision: Union[str, Sequence[str], None] = 'd1a02fc42224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exams_is_deleted'), 'exams', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exams_tenant_id'), 'exams', ['tenant_id'], unique=False, schema='exam')
    op.create_table('exam_schedules',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('full_marks', sa.Float(), nullable=False),
    sa.Column('pass_marks', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exams.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['academic.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exam_schedules_is_deleted'), 'exam_schedules', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_schedules_tenant_id'), 'exam_schedules', ['tenant_id'], unique=False, schema='exam')
    op.create_table('exam_results',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('exam_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['student.enrollments.id'], ),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam.exam_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exam_results_is_deleted'), 'exam_results', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_results_tenant_id'), 'exam_results', ['tenant_id'], unique=False, schema='exam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_exam_results_tenant_id'), table_name='exam_results', schema='exam')
    op.drop_index(op.f('ix_exam_exam_results_is_deleted'), table_name='exam_results', schema='exam')
    op.drop_table('exam_results', schema='exam')
    op.drop_index(op.f('ix_exam_exam_schedules_tenant_id'), table_name='exam_schedules', schema='exam')
    op.drop_index(op.f('ix_exam_exam_schedules_is_deleted'), table_name='exam_schedules', schema='exam')
    op.drop_table('exam_schedules', schema='exam')
    op.drop_index(op.f('ix_exam_exams_tenant_id'), table_name='exams', schema='exam')
    op.drop_index(op.f('ix_exam_exams_is_deleted'), table_name='exams', schema='exam')
    op.drop_table('exams', schema='exam')
    # ### end Alembic commands ###
