"""Add Student Models

Revision ID: d1a02fc42224
Revises: 4272230197ad
Create Date: 2026-08-18 01:17:32.135965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a02fc42224'
down_revision: Union[str, Sequence[str], None] = '4272230197ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='student'
    )
    op.create_index(op.f('ix_student_guardians_is_deleted'), 'guardians', ['is_deleted'], unique=False, schema='student')
    op.create_index(op.f('ix_student_guardians_phone'), 'guardians', ['phone'], unique=False, schema='student')
    op.create_index(op.f('ix_student_guardians_tenant_id'), 'guardians', ['tenant_id'], unique=False, schema='student')
    op.create_table('students',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('guardian_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['tenant.branches.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['student.guardians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='student'
    )
    op.create_index(op.f('ix_student_students_is_deleted'), 'students', ['is_deleted'], unique=False, schema='student')
    op.create_index(op.f('ix_student_students_tenant_id'), 'students', ['tenant_id'], unique=False, schema='student')
    op.create_table('enrollments',
    sa.Column('enrollment_number', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic.academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['academic.classes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['academic.sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='student'
    )
    op.create_index(op.f('ix_student_enrollments_enrollment_number'), 'enrollments', ['enrollment_number'], unique=False, schema='student')
    op.create_index(op.f('ix_student_enrollments_is_deleted'), 'enrollments', ['is_deleted'], unique=False, schema='student')
    op.create_index(op.f('ix_student_enrollments_tenant_id'), 'enrollments', ['tenant_id'], unique=False, schema='student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_enrollments_tenant_id'), table_name='enrollments', schema='student')
    op.drop_index(op.f('ix_student_enrollments_is_deleted'), table_name='enrollments', schema='student')
    op.drop_index(op.f('ix_student_enrollments_enrollment_number'), table_name='enrollments', schema='student')
    op.drop_table('enrollments', schema='student')
    op.drop_index(op.f('ix_student_students_tenant_id'), table_name='students', schema='student')
    op.drop_index(op.f('ix_student_students_is_deleted'), table_name='students', schema='student')
    op.drop_table('students', schema='student')
    op.drop_index(op.f('ix_student_guardians_tenant_id'), table_name='guardians', schema='student')
    op.drop_index(op.f('ix_student_guardians_phone'), table_name='guardians', schema='student')
    op.drop_index(op.f('ix_student_guardians_is_deleted'), table_name='guardians', schema='student')
    op.drop_table('guardians', schema='student')
    # ### end Alembic commands ###
