"""Add ExamType

Revision ID: e190882b3696
Revises: 854e092a8503
Create Date: 2026-08-18 16:59:35.206421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e190882b3696'
down_revision: Union[str, Sequence[str], None] = '854e092a8503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='exam'
    )
    op.create_index(op.f('ix_exam_exam_types_is_deleted'), 'exam_types', ['is_deleted'], unique=False, schema='exam')
    op.create_index(op.f('ix_exam_exam_types_tenant_id'), 'exam_types', ['tenant_id'], unique=False, schema='exam')
    op.add_column('exams', sa.Column('exam_type_id', sa.Uuid(), nullable=True), schema='exam')
    op.create_foreign_key(None, 'exams', 'exam_types', ['exam_type_id'], ['id'], source_schema='exam', referent_schema='exam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', schema='exam', type_='foreignkey')
    op.drop_column('exams', 'exam_type_id', schema='exam')
    op.drop_index(op.f('ix_exam_exam_types_tenant_id'), table_name='exam_types', schema='exam')
    op.drop_index(op.f('ix_exam_exam_types_is_deleted'), table_name='exam_types', schema='exam')
    op.drop_table('exam_types', schema='exam')
    # ### end Alembic commands ###
